In [1]:
import numpy as np

In [8]:
tensor = np.arange(32).reshape([4,2,4])

In [9]:
tensor

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31]]])

In [10]:
np.sum(tensor, axis=0)

array([[48, 52, 56, 60],
       [64, 68, 72, 76]])

In [6]:
np.sum(tensor, axis=1)

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [7]:
np.sum(tensor, axis=2)

array([[ 6, 22, 38],
       [54, 70, 86]])

In [14]:
np.ndim(tensor)

3

# Ground 2

In [2]:
import numpy as np

In [3]:
m = np.arange(6).reshape([2,3])

In [4]:
np.sum(m, axis=0)

array([3, 5, 7])

In [24]:
np.sum(m, axis=1)

array([ 3, 12])

# Ground 3

In [1]:
from tensorflow.python.client import device_lib

In [2]:
device_lib.list_local_devices()

[name: "/device:CPU:0"
 device_type: "CPU"
 memory_limit: 268435456
 locality {
 }
 incarnation: 3407635173725108333]

# Inspection

In [16]:
import inspect

In [29]:
def scan(obj):
    scaned = {}
    scaned['ismodule'] = inspect.ismodule(obj)
    scaned['isclass'] = inspect.isclass(obj)
    scaned['ismethod'] = inspect.ismethod(obj)
    scaned['isfunction'] = inspect.isfunction(obj)
    scaned['isgeneratorfunction'] = inspect.isgeneratorfunction(obj)
    scaned['isgenerator'] = inspect.isgenerator(obj)
    scaned['iscoroutinefunction'] = inspect.iscoroutinefunction(obj)
    scaned['iscoroutine'] = inspect.iscoroutine(obj)
    scaned['isawaitable'] = inspect.isawaitable(obj)
    scaned['isasyncgenfunction'] = inspect.isasyncgenfunction(obj)
    scaned['isasyncgen'] = inspect.isasyncgen(obj)
    scaned['istraceback'] = inspect.istraceback(obj)
    scaned['isframe'] = inspect.isframe(obj)
    scaned['iscode'] = inspect.iscode(obj)
    scaned['isbuiltin'] = inspect.isbuiltin(obj)
    scaned['isroutine'] = inspect.isroutine(obj)
    scaned['isabstract'] = inspect.isabstract(obj)
    scaned['ismethoddescriptor'] = inspect.ismethoddescriptor(obj)
    scaned['isdatadescriptor'] = inspect.isdatadescriptor(obj)
    scaned['isgetsetdescriptor'] = inspect.isgetsetdescriptor(obj)
    scaned['ismemberdescriptor'] = inspect.ismemberdescriptor(obj)
    
    for v in [k for k in scaned.keys() if scaned[k] == True]:
        print('{} = True'.format(v))


# Web Crawling

#### webdriver 사용하여 엑셀 파일 다운로드

In [160]:
from selenium import webdriver

driver = webdriver.Chrome('d:/mydevroot/ws/webdrivers/chromedriver.exe')
#driver2 = webdriver.Edge('d:/mydevroot/ws/webdrivers/MicrosoftWebDriver.exe')

driver.get('http://data.gm.go.kr/portal/data/service/selectServicePage.do?infId=00915CNL1L977ETDR65913')
#sheet-excel-button

from selenium.webdriver.common.keys import Keys
e = driver.find_element_by_id('sheet-excel-button')

e.click()

#### 다운로드된 파일 찾기

In [206]:
download_folder = os.path.join(os.getenv('USERPROFILE'), 'Downloads')

file_list = { e.name: e.stat().st_ctime for e in os.scandir(download_folder) if e.is_file() == True }

from collections import Counter
counter = Counter(file_list)
ordered = sorted(counter, key=lambda x: x[1], reverse=True)

downloaded_file = os.path.join(download_folder, ordered[0])

#### pandas 로 엑셀파일 읽기

In [209]:
import numpy as np
import pandas as pd

In [211]:
df = pd.read_excel(downloaded_file)

In [219]:
np.sum(df.isna(), axis=0)

건축구분명     0
대지위치      0
연면적       0
허가일자      0
총주차대수     1
세대수      12
호수       10
가구수      14
dtype: int64

In [220]:
df

건축구분명                                대지위치       연면적        허가일자  총주차대수  \
0     신축                  경기도 광명시 소하동 1398-4   190.280  2018-01-08    2.0   
1     증축                   경기도 광명시 일직동 358-5   231.000  2018-01-16    2.0   
2     신축                   경기도 광명시 광명동 277-9   217.177  2018-01-17    3.0   
3     신축                   경기도 광명시 광명동 758-4  1452.000  2018-01-19   20.0   
4   용도변경                    경기도 광명시 철산동 93-2   458.250  2018-01-22    2.0   
5   용도변경                    경기도 광명시 소하동 1342  7025.890  2018-01-22   42.0   
6   용도변경                    경기도 광명시 소하동 1342  7025.890  2018-01-22   42.0   
7   용도변경                    경기도 광명시 소하동 1342  7025.890  2018-01-22   42.0   
8   용도변경                    경기도 광명시 소하동 1342  7025.890  2018-01-22   42.0   
9   용도변경                    경기도 광명시 소하동 1342  7025.890  2018-01-22   42.0   
10  용도변경                  경기도 광명시 광명동 374-53   349.490  2018-01-24    NaN   
11    신축                  경기도 광명시 소하동 1077-4   321.520  2018-01-26    7.0   
12    신축               경기도 광명시 소하동 35-2 외4필지   867.920  2018-01-29    6.0   
13    신축  경기도 광명시 광명동 광명재정비촉진지구 광명16R구역 16-3   767.920  2018-01-31    4.0   
14    신축                경기도 광명시 소하동 947 외2필지   497.640  2018-01-31    8.0   
15    신축              경기도 광명시 소하동 947-6 외1필지   497.640  2018-01-31    8.0   
16    신축                   경기도 광명시 소하동 947-6   497.640  2018-01-31    8.0   

    세대수    호수  가구수  
0   1.0   NaN  NaN  
1   NaN   NaN  NaN  
2   NaN   NaN  3.0  
3   8.0  12.0  NaN  
4   NaN   NaN  2.0  
5   NaN  40.0  NaN  
6   NaN  40.0  NaN  
7   NaN  40.0  NaN  
8   NaN  40.0  NaN  
9   NaN  40.0  NaN  
10  NaN   NaN  1.0  
11  NaN   NaN  NaN  
12  NaN   7.0  NaN  
13  NaN   NaN  NaN  
14  8.0   NaN  NaN  
15  8.0   NaN  NaN  
16  8.0   NaN  NaN

## Windows Registry

In [2]:
import winreg

In [8]:
hkey = winreg.OpenKey(winreg.HKEY_CURRENT_USER, 'Control Panel\\Desktop')

In [33]:
def confirm_key(key, sub_key, reg_dt, value):
    try:
        wk = winreg.OpenKeyEx(key, sub_key, 0, winreg.KEY_ALL_ACCESS)
    except FileNotFoundError:
        wk = winreg.CreateKeyEx(key, sub_key, 0, winreg.KEY_ALL_ACCESS)
    finally:
        winreg.SetValueEx(key, sub_key, 0, reg_dt, value)
        wk.Close()

In [36]:
#confirm_key(hkey, 'KKK', winreg.REG_DWORD, 10)
confirm_key(hkey, 'SCRNSAVE.EXE', winreg.REG_SZ, 'With POSCO.scr')

PermissionError: [WinError 5] 액세스가 거부되었습니다

## OpenCV

참조사이트: http://blog.naver.com/samsjang/220501624273

In [38]:
%matplotlib inline
import cv2
import numpy as np
import matplotlib.pyplot as plt

In [40]:
img = cv2.imread('images/car.png', cv2.IMREAD_COLOR)

In [41]:
cv2.imshow('model', img)

In [42]:
cv2.waitKey(0)

32

In [43]:
cv2.destroyAllWindows()

### camera

In [63]:
cap = cv2.VideoCapture(0)

cap.set(3, 480)
cap.set(4, 320)

True

In [64]:
while True:
    ret, frame = cap.read()
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    cv2.imshow('video', gray)
    k = cv2.waitKey(1) & 0xFF
    if k == 27: // ESC
        break
        
cap.release()
cv2.destroyAllWindows()        

## Web Scrapping

In [31]:
import warnings

In [32]:
warnings.filterwarnings('ignore')

In [29]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from bs4 import BeautifulSoup

driver = webdriver.Chrome('d:/mydevroot/ws/webdrivers/chromedriver.exe')

driver.get('https://www.data.go.kr')

In [30]:
driver.set_window_size(1696, 1026)
driver.find_element_by_link_text('데이터셋').click()
driver.find_element_by_link_text('제공기관필터').click()
driver.find_element_by_css_selector('#insttFFList > li > a > span').click()
driver.find_element_by_link_text('파일데이터 결과 더보기').click()
driver.find_element_by_link_text('2').click()
driver.file_detector()

In [27]:
driver.close()

## 도시공원

In [33]:
!pip show plotnine

Name: plotnine
Version: 0.5.1
Summary: A grammar of graphics for python
Home-page: https://github.com/has2k1/plotnine
Author: None
Author-email: None
License: GPL-2
Location: c:\users\s11711\appdata\local\programs\python\python36\lib\site-packages
Requires: scipy, statsmodels, matplotlib, numpy, mizani, pandas, descartes, patsy
Required-by: 


In [34]:
!pip install folium

In [61]:
%pwd

'd:\\mydevroot\\ws'

In [62]:
import pandas as pd
import numpy as np
from plotnine import *
import re
import folium

In [67]:
#park = pd.read_csv('./data/전국도시공원표준데이터.csv', encoding='euc-kr')
!dir data

 D 드라이브의 볼륨: Data
 볼륨 일련 번호: E850-0409

 d:\mydevroot\ws\data 디렉터리

2019-01-07  오후 01:01    <DIR>          .
2019-01-07  오후 01:01    <DIR>          ..
2019-01-07  오후 01:00         3,382,129 전국도시공원표준데이터.csv
               1개 파일           3,382,129 바이트
               2개 디렉터리  390,112,985,088 바이트 남음


## EP Login Script

In [33]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from bs4 import BeautifulSoup

driver = webdriver.Chrome('d:/mydevroot/ws/webdrivers/chromedriver.exe')
driver.get('*******')

In [34]:
driver.window_handles

['CDwindow-9B557A75CDAD1D9042E32D5F5D14F942']

In [35]:
driver.maximize_window()
driver.find_element_by_id('username').send_keys('*******')
driver.find_element_by_id('password').send_keys('*******')
driver.find_element_by_id('Login').submit()

In [36]:
driver.switch_to.alert.accept()

In [37]:
driver.window_handles

['CDwindow-9B557A75CDAD1D9042E32D5F5D14F942',
 'CDwindow-6A7C6DB08EB2B386F8CC19EA3EED9996']

In [38]:
driver.find_element_by_css_selector('img[title="전자결재"]').click()

In [39]:
driver.window_handles

['CDwindow-9B557A75CDAD1D9042E32D5F5D14F942',
 'CDwindow-6A7C6DB08EB2B386F8CC19EA3EED9996',
 'CDwindow-BF1F95A8692C33153A32CCA012DFE6C5']

In [40]:
driver.switch_to.window(driver.window_handles[2])

In [44]:
driver.switch_to.frame(driver.find_element_by_css_selector('iframe[name=REA_contents'))

In [45]:
driver.find_element_by_id('rptHighLevel_ctl02_rptMiddleLevel_ctl01_lnkName').click()

In [46]:
driver.implicitly_wait(1)

In [47]:
driver.close()

In [48]:
driver.quit()

## Data Loader

* 

In [139]:
import abc
import pandas as pd
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import os
import os.path
import datetime

class PublicDataLoader(metaclass=abc.ABCMeta):
    """공공데이타 포탈에 공개된 데이타를 추출하여 pandas DataFrame 으로 반환
    Chrome available preference: https://cs.chromium.org/chromium/src/chrome/common/pref_names.cc
    """
    
    def __init__(self, url):
        self._url = url
        
    def load_as_dataframe(self):
        return self.extract()
    
    @property
    def url(self):
        return self._url
    
    @abc.abstractmethod
    def extract(self):
        pass
    
    @property
    def about(self):
        return self._about()
    
    @abc.abstractclassmethod
    def _about():
        pass
    
    def _create_webdriver(self, options=None):
        return webdriver.Chrome('d:/mydevroot/ws/webdrivers/chromedriver.exe', options=options)
    
    @staticmethod
    def _find_latest_file(path=None):
        import os
        from collections import Counter
        path = os.getcwd() if path==None else path
        file_list = {e.name: e.stat().st_ctime for e in os.scandir(path) if e.is_file() == True}
        counter = Counter(file_list)
        ordered = sorted(counter, key=lambda x: x[1], reverse=True)
        _, ext = os.path.splitext(ordered[0])
        renamed_filename = str(datetime.datetime.now().toordinal()) + ext  
        os.system('ren "{}" "{}'.format(os.path.join(path, ordered[0]), renamed_filename))            
        return  os.path.join(path, renamed_filename)
    
class JunkukDosiGongwon(PublicDataLoader):
    def __init__(self):
        super().__init__('https://www.data.go.kr/dataset/15012890/standard.do')
        self.__driver = None
        
    def __del__(self):
        self.__driver.close()
        
    def extract(self):
        download_folder = r'c:\Users\s11711\downloads\Text'
        options = Options()
        options.add_experimental_option('prefs', {
            'download.default_directory': download_folder,
            'download.prompt_for_download': False,
            'download.directory_upgrade': True,
            'safebrowsing.enabled': True
        })
        self.__driver = super()._create_webdriver(options)
        self.__driver.get(self.url)
        self.__driver.find_element_by_css_selector('.single-download-btn').click()
        self.__driver.implicitly_wait(5)
        filename = PublicDataLoader._find_latest_file(download_folder)
        return pd.read_csv(filename, sep='\t')
        #return filename
    
    def _about(self):
        return '전국도시공원 표준데이타'

In [140]:
a = JunkukDosiGongwon()

In [141]:
df = a.extract()

IndexError: list index out of range

In [138]:
del a

In [154]:
f = open(r'C:\Users\S11711\Downloads\Text\전국도시공원표준데이터 (1).xls', encoding='euc-kr')

In [153]:
f.readlines()

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 0: invalid continuation byte

In [39]:
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

options = Options()
options.add_experimental_option('prefs', {
    'download.default_directory': r'c:\Users\s11711\downloads\Text',
    'download.prompt_for_download': False,
    'download.directory_upgrade': True,
    'safebrowsing.enabled': True
})
driver = webdriver.Chrome('d:/mydevroot/ws/webdrivers/chromedriver.exe',options=options)

## 전국도시공원 표준데이타(

* 출처: 오늘코드
* Youtube: https://www.youtube.com/watch?v=uJ6QO6jLBWA
* 데이타: https://www.data.go.kr/dataset/15012890/standard.do

In [49]:
import warnings
warnings.filterwarnings('ignore')

In [50]:
import pandas as pd
import numpy as np
from plotnine import *
import folium
import re

In [68]:
#-*- encoding: utf-8 -*-
park = pd.read_csv('data\park.csv', sep='\t')
park.shape

(16096, 19)

In [ ]:
park.columns

In [ ]:
park.head(5)

In [ ]:
park.isnull().sum() # 결측치 검사

In [ ]:
import missingno as msno
msno.matrix(park)